name: auckland_ml_summit
channels:
  - defaults
dependencies:
  - cloudpickle=0.6.1
  - python=3.6
  - numpy
  - pandas=0.24.1
  - scikit-learn=0.20.2
  - matplotlib=3.0.2
  - seaborn=0.9.0
  - pip:
    - mlflow
